DURATION_METHODS = [
    "preheat", "cook", "bake", "boil", "broil", "poach", 
    "sauté", "simmer", "roast", "toast", "chill", "freeze", 
    "marinate", "grill", "steam", "blanch", "fry", "knead",
    "boil", "reduce"
]
NO_DURATION_METHODS = [
    "drain", "transfer", "mix", "chop", "grate", "cut", 
    "stir", "gather", "mash", "add", "sprinkle", "serve",
    "whisk", "dice", "slice", "fold", "pour", "peel", 
    "crack", "press", "spread", "combine", "coat", 
    "layer", "shape"
]

NAMES = [
    "bowl",
    "pan",
    "dish",
    "pot",
    "skillet",
    "tray",
    "baking sheet",
    "baking dish",
    "saucepan",
    "oven",
    "baking pan",
    "casserole dish",
    "wok",
    "dutch oven",
    "grill pan",
    "roasting pan",
    "pie dish",
    "loaf pan",
    "muffin tin",
    "pizza stone",
    "ramekin",
    "stockpot",
    "custard cup",
    "brotform"
]

TOOLS = [
    "knife",
    "spoon",
    "fork",
    "whisk",
    "tongs",
    "spatula",
    "grater",
    "peeler",
    "ladle",
    "rolling pin",
    "measuring cup",
    "measuring spoon",
    "mixing bowl",
    "cutting board",
    "colander",
    "strainer",
    "sifter",
    "timer",
    "thermometer",
    "scale",
    "oven mitt",
    "pot holder",
    "baking rack",
    "baking paper",
    "parchment paper",
    "aluminum foil",
    "plastic wrap",
    "wax paper",
    "tinfoil",
    "towel",
    "paper towel",
    "dish towel",
    "dish cloth",
    "pastry cutter",
    "mandoline slicer",
    "kitchen shears",
    "garlic press",
    "zester",
    "juicer",
    "meat tenderizer",
    "pastry brush",
    "bench scraper",
    "can opener",
    "bottle opener",
    "melon baller",
    "ice cream scoop",
    "mortar and pestle",
    "slotted spoon",
    "offset spatula",
    "pastry bag",
    "candy thermometer",
    "kitchen blowtorch",
    "egg slicer",
    "toaster",
    "blender",
    "food processor",
    "immersion blender",
    "electric mixer",
    "rice cooker",
    "pressure cooker",
    "sous-vide machine",
    "griddle",
    "tea strainer",
    "coffee grinder",
    "cheesecloth",
    "pizza cutter",
    "grill press",
    "baster",
    "splatter guard",
    "tamper",
    "spätzle maker"
]